In [14]:
import openpyxl
import pandas as pd
days = openpyxl.load_workbook("D02EXAMPLE.xlsx").sheetnames[:7]

In [16]:
udf = pd.DataFrame([]) # 빈 DataFrame을 만듬
for i in days:
    udf1 = pd.read_excel("D02EXAMPLE.xlsx", sheet_name=i).set_index("제품")
    udf1 = udf1.stack().reset_index()
    udf1.columns = ["제품", "지점", "매출"]
    udf1["날짜"] = i
    udf = pd.concat([udf, udf1])
udf

               제품      지점       매출          날짜
0     종합어묵 (300g)     강남점  1930000  2021-08-30
1     종합어묵 (300g)     서초점  1350000  2021-08-30
2     종합어묵 (300g)     송파점   630000  2021-08-30
3     종합어묵 (300g)     노원점   420000  2021-08-30
4     종합어묵 (300g)     은평점  1360000  2021-08-30
...           ...     ...      ...         ...
3395  멸치가루 (120g)    동인천점  1120000  2021-10-11
3396  멸치가루 (120g)     분당점  1440000  2021-10-11
3397  멸치가루 (120g)     일산점  1700000  2021-10-11
3398  멸치가루 (120g)     부평점  1230000  2021-10-11
3399  멸치가루 (120g)  부천 옥길점   540000  2021-10-11

[23800 rows x 4 columns]

In [22]:
df1 = pd.read_excel("D02EXAMPLE.xlsx", sheet_name="지점구분")
df2 = pd.read_excel("D02EXAMPLE.xlsx", sheet_name="제품구분")
pdf1 = udf.merge(df1, how="left").merge(df2, how='left')
pdf1

                제품      지점       매출          날짜  지역    분류  구분
0      종합어묵 (300g)     강남점  1930000  2021-08-30  서울   직영점  기타
1      종합어묵 (300g)     서초점  1350000  2021-08-30  서울   직영점  기타
2      종합어묵 (300g)     송파점   630000  2021-08-30  서울  비직영점  기타
3      종합어묵 (300g)     노원점   420000  2021-08-30  서울  비직영점  기타
4      종합어묵 (300g)     은평점  1360000  2021-08-30  서울  비직영점  기타
...            ...     ...      ...         ...  ..   ...  ..
23795  멸치가루 (120g)    동인천점  1120000  2021-10-11  인천   직영점  기타
23796  멸치가루 (120g)     분당점  1440000  2021-10-11  경기  비직영점  기타
23797  멸치가루 (120g)     일산점  1700000  2021-10-11  경기   직영점  기타
23798  멸치가루 (120g)     부평점  1230000  2021-10-11  인천  비직영점  기타
23799  멸치가루 (120g)  부천 옥길점   540000  2021-10-11  경기   직영점  기타

[23800 rows x 7 columns]

In [27]:
pdf1.pivot_table("매출", index="날짜", columns="지역", aggfunc="sum").to_clipboard()
pdf1.pivot_table("매출", index="지역", columns="구분", aggfunc="sum").to_clipboard()

In [ ]:
# 전체코드
import pandas as pd
import openpyxl
days = openpyxl.load_workbook("D02EXAMPLE.xlsx").sheetnames[:7]
udf = pd.DataFrame([])
for i in days:
    udf1 = pd.read_excel("D02EXAMPLE.xlsx", sheet_name=i).set_index("제품")  
    udf1 = udfi.stack().reset_index()
    udf1.columns=["제품", "지점","매출"]
    udf1["날짜"] = i
    udf = pd.concat([udf,udf1])
df1 = pd.read_excel("D02EXAMPLE.xlsx", sheet_name="지점구분")
df2 = pd.read_excel("D02EXAMPLE.xlsx", sheet_name="제품구분")
pdf1 = udf.merge(df1, how="left").merge(df2, how="left")
pdf1.pivot_table("매출", index="날짜", columns="지역", aggfunc="sum").to_clipboard()
pdf1.pivot_table("매출", columns="구분", index="지역", aggfunc="sum").to_clipboard()